server:
  port: 8002
spring:
  application:
    name: provider-user-v1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka



info:
  app.name: 这是一个 SpringCloud 项目的用户消息提供者：provider-user-v1
  author: 刘仁奎
