
spring:
  profiles: server2
server:
  port: 10002
eureka:
  instance:
    hostname: eureka-server2
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:10001/eureka/,http://eureka-server3:10003/eureka/


